### ISSUE TITLE
FoodX>> Customer>> Tip payment (High Priority)

### ISSUE THREAD

**Issue by srinivasmudhiraj3** [QSPaysys1/FoodX-Testing#13]
**ISSUE:-** After adding TIP to delivery executive, there was no confirmation and information about the TIP money.

https://github.com/user-attachments/assets/ca06d752-68ff-4ef0-a84c-feb4c150c060

**Comment by sankarnagarapu** [comment]
Resolved

**Comment by srinivasmudhiraj3** [comment]
Tip payment was still not reflecting on the customers bill and admin panel, please check once again

**Comment by sankarnagarapu** [comment]
Resolved
